// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://delonfqziulcmdyqefzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbG9uZnF6aXVsY21keXFlZnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyODU1NzQsImV4cCI6MjA4OTg2MTU3NH0.0r7YQTR5Unf_8iXDuZp564UByMy1E5f8Rvm1NE2oafk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});